# https://github.com/bitnami/charts/tree/master/bitnami/redis
replicaCount: 1
collectionReplicas: 1

auth:
  enabled: false
  sentinel: false

master:
  nodeSelector:
    kubernetes.io/os: linux

replica:
  replicaCount: 1
  nodeSelector:
    kubernetes.io/os: linux
