# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

deplyment:
  replicas: 1
  
dashboard:
  enabled: true

service:
  spec:
    externalTrafficPolicy: Local

hostNetwork: true

ports:
  web:
    port: 80
    redirectTo: websecure
  websecure:
    port: 443

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0