version: "2.4"

x-dapr:
  &default-dapr
  image: daprio/daprd:1.3.0
  restart: always
  volumes:
    - ./beholder-dapr/:/dapr:ro
    
services:
  ###############################################
  # Beholder Cortex
  beholder-cortex:
    image: beholderrpa/iot-cortex
    container_name: beholder-cortex
    restart: always
    networks:
      - backend
    labels: 
      - traefik.enable=true
      - traefik.http.routers.cortex.rule=Host(`${BEHOLDER_CORTEX_HOSTNAME}`)
      - traefik.http.routers.cortex.entrypoints=websecure
      - traefik.http.routers.cortex.tls=true
      - traefik.http.services.cortex.loadbalancer.server.port=3000
    volumes: 
      - ./beholder-traefik/certs/server.crt:/srv/app/certs/server.crt
  # Dapr Sidecar
  beholder-cortex-dapr:
    << : *default-dapr
    container_name: beholder-cortex-dapr
    command: ["./daprd",
      "-app-id", "cortex",
      "-app-port", "3000",
      "-dapr-http-max-request-size", "16",
      "-placement-host-address", "beholder-dapr-placement:50006",
      "-components-path", "/dapr/components",
      "-config", "/dapr/config.yaml"]
    depends_on:
      - beholder-cortex
      - beholder-nexus
    network_mode: "service:beholder-cortex"
  ###############################################
  # Beholder Cerebrum (Node Red)
  beholder-cerebrum:
    image: beholderrpa/iot-cerebrum-v1
    container_name: beholder-cerebrum
    restart: always
    environment:
      - BEHOLDER_STALK_NAME=${BEHOLDER_SHORT_HOSTNAME}
    networks:
      - backend
    labels:
      - traefik.enable=true
      # Proxy to authenticated content
      - traefik.http.routers.beholder_cerebrum.rule=Host(`${BEHOLDER_CEREBRUM_HOSTNAME}`)
      - traefik.http.routers.beholder_cerebrum.entrypoints=websecure
      - traefik.http.routers.beholder_cerebrum.tls=true
      - traefik.http.routers.beholder_cerebrum.service=beholder_cerebrum
      - traefik.http.services.beholder_cerebrum.loadbalancer.server.port=1880
  ###############################################
  # Beholder Nexus
  beholder-nexus:
    image: emqx/emqx:4.3.5
    container_name: beholder-nexus
    restart: always
    expose: 
      # Dashboard Port
      - 18083
      # Emqx Port
      - 11883
      # MQTT Port
      - 1883
      # MQTT SSL Port
      - 8883
      # MQTT Web Sockets Port
      - 8083
      # MQTT Web Sockets Secure Port
      - 8084
    networks:
      - backend
    labels:
      - traefik.enable=true
      # Proxy to authenticated content
      - traefik.http.routers.beholder_nexus.rule=Host(`${BEHOLDER_NEXUS_HOSTNAME}`)
      - traefik.http.routers.beholder_nexus.entrypoints=websecure
      - traefik.http.routers.beholder_nexus.tls=true
      - traefik.http.routers.beholder_nexus.service=beholder_nexus
      - traefik.http.services.beholder_nexus.loadbalancer.server.port=18083
      # Proxy mqtt web sockets
      - traefik.http.middlewares.beholder_nexus_mqtt_ws_stripprefixregex.stripprefixregex.regex=/nexus/
      - traefik.http.routers.beholder_nexus_mqtt_ws.rule=Host(`${BEHOLDER_CORTEX_HOSTNAME}`) && PathPrefix(`/nexus`)
      - traefik.http.routers.beholder_nexus_mqtt_ws.entrypoints=websecure
      - traefik.http.routers.beholder_nexus_mqtt_ws.tls=true
      - traefik.http.routers.beholder_nexus_mqtt_ws.middlewares=beholder_nexus_mqtt_ws_stripprefixregex
      - traefik.http.routers.beholder_nexus_mqtt_ws.service=beholder_nexus_mqtt_ws
      - traefik.http.services.beholder_nexus_mqtt_ws.loadbalancer.server.port=8083
      # Proxy mqtt
      - traefik.tcp.routers.beholder_nexus_mqtt.rule=HostSNI(`${BEHOLDER_NEXUS_HOSTNAME}`)
      - traefik.tcp.routers.beholder_nexus_mqtt.entrypoints=mqtt
      - traefik.tcp.services.beholder_nexus_mqtt.loadbalancer.server.port=1883
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
  ###############################################
  # Beholder Stalk
  beholder-stalk:
    image: beholderrpa/iot-stalk-v2
    container_name: beholder-stalk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    environment:
      - BEHOLDER_STALK_NAME=${BEHOLDER_SHORT_HOSTNAME}
      - beholder_stalk_keymin=40
      - beholder_stalk_keymax=80
    networks:
      - backend
    depends_on:
      - beholder-nexus
  ###############################################
  # Beholder Epidermis
  beholder-epidermis:
    image: beholderrpa/iot-epidermis-v1
    container_name: beholder-epidermis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    environment:
      - BEHOLDER_EPIDERMIS_NAME=${BEHOLDER_SHORT_HOSTNAME}
    networks:
      - backend
    depends_on:
      - beholder-nexus
    labels:
      - traefik.enable=true
      # Proxy to authenticated content
      - traefik.http.routers.beholder_epidermis.rule=Host(`${BEHOLDER_CORTEX_HOSTNAME}`) && PathPrefix(`/api/epidermis`)
      - traefik.http.routers.beholder_epidermis.entrypoints=websecure
      - traefik.http.routers.beholder_epidermis.tls=true
      - traefik.http.routers.beholder_epidermis.service=beholder_epidermis
      - traefik.http.services.beholder_epidermis.loadbalancer.server.port=80
  # Dapr Sidecar
  beholder-epidermis-dapr:
    << : *default-dapr
    container_name: beholder-epidermis-dapr
    command: ["./daprd",
      "-app-id", "epidermis",
      "-app-port", "80",
      "-dapr-http-max-request-size", "16",
      "-placement-host-address", "beholder-dapr-placement:50006",
      "-components-path", "/dapr/components",
      "-config", "/dapr/config.yaml"]
    depends_on:
      - beholder-epidermis
      - beholder-nexus
    network_mode: "service:beholder-epidermis"
  ###############################################
  # Beholder Grafana
  beholder-grafana:
    image: grafana/grafana
    container_name: beholder-grafana
    restart: always
    environment:
      GF_LOG_MODE: console
    networks:
      - backend
    volumes:
      - ./beholder-grafana:/etc/grafana/:ro
      - grafana_data:/var/lib/grafana:rw
    labels: 
      - traefik.enable=true
      # Proxy to authenticated content
      - traefik.http.routers.beholder_grafana.rule=Host(`${BEHOLDER_GRAFANA_HOSTNAME}`)
      - traefik.http.routers.beholder_grafana.entrypoints=websecure
      - traefik.http.routers.beholder_grafana.tls=true
      - traefik.http.services.beholder_grafana.loadbalancer.server.port=3000
  ###############################################
  # Beholder Postgres
  beholder-postgres:
    image: postgres
    container_name: beholder-postgres
    restart: always
    environment:
      POSTGRES_USER: beholder
      POSTGRES_PASSWORD: beholder
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
    volumes:
      - ./beholder-postgres/initdb/:/docker-entrypoint-initdb.d/:ro
      - postgres_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  ###############################################
  # Beholder Prefrontal Redis
  beholder-prefrontal:
    image: redis
    container_name: beholder-prefrontal
    restart: always
    networks:
      - backend
    volumes:
      - prefrontal_redis_data:/data:rw
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  ###############################################
  # Dapr placement service
  beholder-dapr-placement:
    image: daprio/dapr
    container_name: beholder-dapr-placement
    restart: always
    command: ["./placement", "-port", "50006"]
    networks:
      - backend
  ###############################################
  # Beholder Reverse Proxy
  beholder-traefik:
    image: traefik:v2.4
    container_name: beholder-traefik
    restart: always
    command:
      - "--ping=true"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.amqp.address=:5672"
      - "--entrypoints.mqtt.address=:1883"
      - "--entrypoints.redis.address=:6379"
      - "--providers.file.filename=/etc/traefik/conf/dynamic_conf.yml"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend
    volumes:
      - ./beholder-traefik/certs:/etc/traefik/certs/:ro
      - ./beholder-traefik/conf:/etc/traefik/conf/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 3s
      retries: 30
networks:
  frontend:
  backend:

volumes:
  prefrontal_redis_data:
  postgres_data:
  grafana_data:
