version: "2.4"

services:
  ###############################################
  # Beholder Cortex
  beholder-cortex:
    image: beholderrpa/iot-cortex:latest
    build:
      context: ./beholder-cortex
      dockerfile: Dockerfile.dev
    volumes:
      - ./beholder-cortex:/srv/app:rw
      - beholder_cortex_node_modules:/srv/app/node_modules
      - beholder_cortex_next:/srv/app/.next
  ###############################################
  # Beholder Cerebrum (Node Red)
  beholder-cerebrum:
    image: beholderrpa/iot-cerebrum-v1:latest
    build:
      context: ./beholder-cerebrum
      dockerfile: Dockerfile.dev
    volumes:
      - ./beholder-cerebrum/data:/data:rw
  ###############################################
  # Beholder Nexus
  beholder-nexus:
    ports:
      - 1883:1883
  ###############################################
  # Beholder Stalk
  beholder-stalk:
    image: beholderrpa/iot-stalk-v2:latest
    build:
      context: ./beholder-stalk-v2
      dockerfile: Dockerfile.dev
    ports:
      - 7000:80
    volumes:
      - ./usb-dev/hidg0:/dev/hidg0
      - ./usb-dev/hidg1:/dev/hidg1
      - ./usb-dev/hidg2:/dev/hidg2
  ###############################################
  # Beholder Occipital
  beholder-occipital:
    image: beholderrpa/iot-occipital-v1:latest
    build:
      context: ./beholder-occipital-v1
      dockerfile: Dockerfile.dev
    ports:
      - 7001:80
  ###############################################
  # Beholder Epidermis
  beholder-epidermis:
    image: beholderrpa/iot-epidermis-v1:latest
    build:
      context: ./beholder-epidermis-v1
      dockerfile: Dockerfile.dev
    ports:
      - 7002:80
  ###############################################
  # Beholder Postgres
  beholder-postgres:
    image: postgres:latest
    ports:
      - 5432:5432
  ###############################################
  # Beholder Adminer
  beholder-adminer:
    image: adminer
    container_name: beholder-adminer
    restart: always
    depends_on:
      - beholder-postgres
    ports:
      - 8082:8080
    networks:
      - backend
  ###############################################
  # Dapr placement service
  beholder-dapr-placement:
    ports: 
      - 6050:50006
  ###############################################
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: beholder-jaeger
    restart: always
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - 9411:9411
    networks:
      - backend
    labels:
      - traefik.enable=true
      # Host TLS jaeger site
      - traefik.http.routers.jaeger.rule=Host(`${BEHOLDER_JAEGER_HOSTNAME}`)
      - traefik.http.routers.jaeger.entrypoints=websecure
      - traefik.http.routers.jaeger.tls=true
      - traefik.http.services.jaeger.loadbalancer.server.port=16686
  ###############################################
  # Beholder Reverse Proxy
  beholder-traefik:
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`${BEHOLDER_TRAEFIK_HOSTNAME}`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.service=api@internal
volumes:
  beholder_cortex_node_modules:
  beholder_cortex_next: