version: "2.4"

services:
  ###############################################
  # Beholder Cortex
  beholder-cortex:
    image: beholderrpa/iot-cortex-arm32v7:master
  beholder-cortex-dapr:
    image: daprio/daprd:latest
  ###############################################
  # Beholder Cerebrum (Node Red)
  beholder-cerebrum:
    image: beholderrpa/iot-cerebrum-v1:master
    volumes:
      - cerebrum_data:/data:rw
  beholder-cerebrum-dapr:
    image: daprio/daprd:latest
  ###############################################
  # Beholder Stalk
  beholder-stalk:
    image: beholderrpa/iot-stalk-v2-arm32v7:master
    devices:
      - "/dev/hidg0:/dev/hidg0"
      - "/dev/hidg1:/dev/hidg1"
      - "/dev/hidg2:/dev/hidg2"
  beholder-stalk-dapr:
    image: daprio/daprd:latest
  ###############################################
  # Beholder Occipital
  beholder-occipital:
    image: beholderrpa/iot-occipital-v1-arm32v7:master
  beholder-occipital-dapr:
    image: daprio/daprd:latest
  ###############################################
  # Beholder Nexus
  beholder-nexus:
    # If this is not present, clock_gettime fails
    privileged: true
  ###############################################
  # Beholder Reverse Proxy
  beholder-traefik:
    environment: 
      - beholder_hostname=${BEHOLDER_HOSTNAME}
  ###############################################
  # Watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: beholder-watchtower
    restart: unless-stopped
    environment: 
      - "WATCHTOWER_SCHEDULE=15 * * * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes: 
  cerebrum_data: