version: "2.4"

services:
  ###############################################
  # Beholder Stalk
  beholder-stalk:
    devices:
      - "/dev/hidg0:/dev/hidg0"
      - "/dev/hidg1:/dev/hidg1"
      - "/dev/hidg2:/dev/hidg2"
  ###############################################
  # Beholder Nexus
  beholder-nexus:
    # If this is not present, clock_gettime fails
    privileged: true
  ###############################################
  # Beholder Reverse Proxy
  beholder-traefik:
    environment: 
      - beholder_hostname=${BEHOLDER_HOSTNAME}
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.amqp.address=:5672"
      - "--entrypoints.mqtt.address=:1883"
      - "--entrypoints.redis.address=:6379"
      - "--providers.file.filename=/etc/traefik/conf/dynamic_conf_rpi.yml"
      - "--providers.docker.exposedbydefault=false"
    volumes: 
      - ./beholder-traefik/conf:/etc/traefik/conf/:ro
      - ./beholder-traefik/certs:/etc/traefik/certs/:ro
  ###############################################
  # Watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: beholder-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  