version: "2.4"

services:
  beholder-cortex:
    image: beholderrpa/cortex:latest
    build:
      context: ./beholder-cortex
      dockerfile: Dockerfile.dev
    volumes:
      - './beholder-cortex:/srv/app'
      - 'beholder_cortex_node_modules:/srv/app/node_modules'
    ports:
      - 3000:3000
  beholder-nexus:
    image: beholderrpa/nexus:latest
    ports:
      - 15672:15672 # RabbitMQ Management Port
      - 1883:1883 # MQTT Port 
      - 15675:15675 # MQTT Web Sockets Port
  beholder-stalk:
    image: beholderrpa/stalk:latest
  beholder-grafana:
    image: beholderrpa/grafana:latest
    ports:
      - 3001:3000
  beholder-postgres:
    image: beholderrpa/postgres:latest
    ports:
      - 5432:5432
  beholder-nginx:
    image: beholderrpa/nginx:latest
    build:
      context: ./beholder-nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    volumes:
      - ./beholder-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./beholder-nginx/api_conf.d:/etc/nginx/api_conf.d
  # Utility/Orchestration
  beholder-adminer:
    image: adminer
    container_name: beholder-adminer
    restart: always
    depends_on:
      - beholder-postgres
    ports:
      - 8082:8080
    networks:
      - backend

volumes:
  'beholder_cortex_node_modules':