version: "2.4"

services:
  ###############################################
  # Beholder Cortex
  beholder-cortex:
    image: beholderrpa/iot-cortex-arm64:master
  ###############################################
  # Beholder Cerebrum (Node Red)
  beholder-cerebrum:
    image: beholderrpa/iot-cerebrum-v1:master
    volumes:
      - cerebrum_data:/data:rw
  ###############################################
  # Beholder Stalk
  beholder-stalk:
    image: beholderrpa/iot-stalk-v2:master
    devices:
      - "/dev/hidg0:/dev/hidg0"
      - "/dev/hidg1:/dev/hidg1"
      - "/dev/hidg2:/dev/hidg2"
  ###############################################
  # Beholder Epidermis
  beholder-epidermis:
    image: beholderrpa/iot-epidermis-v1:master
  ###############################################
  # Beholder Nexus
  beholder-nexus:
    # If this is not present, clock_gettime fails
    privileged: true
  ###############################################
  # Beholder Reverse Proxy
  beholder-traefik:
    environment: 
      - beholder_hostname=${BEHOLDER_HOSTNAME}

volumes: 
  cerebrum_data: