http:
  serversTransports:
    titleadmin_app:
      serverName: "titleadmin_app"
    titleadmin_api:
      insecureSkipVerify: true
  services:
    titleadmin_app_frontend:
      loadBalancer:
        serversTransport: "titleadmin_app"
        servers:
          - url: "http://titleadmin_app_frontend:3000/"
    titleadmin_app_auth_sidecar:
      loadBalancer:
        serversTransport: "titleadmin_app"
        servers:
          - url: "http://titleadmin_app_auth_sidecar/"
    titleadmin_santander_auth_sidecar:
      loadBalancer:
        serversTransport: "titleadmin_app"
        servers:
          - url: "http://titleadmin_santander_auth_sidecar/"
    titleadmin_gmf_auth_sidecar:
      loadBalancer:
        serversTransport: "titleadmin_app"
        servers:
          - url: "http://titleadmin_gmf_auth_sidecar/"
    titleadmin_ally_auth_sidecar:
      loadBalancer:
        serversTransport: "titleadmin_app"
        servers:
          - url: "http://titleadmin_ally_auth_sidecar/"
    titleadmin_api_backend:
      loadBalancer:
        serversTransport: "titleadmin_api"
        passHostHeader: false
        servers:
          - url: 'https://{{ env "TITLE_ADMIN_API_HOSTNAME" }}/'
  routers:
    titleadmin_app_frontend:
      rule: 'Host(`{{ env "TITLE_ADMIN_APP_HOSTNAME" }}`)'
      service: "titleadmin_app_frontend"
      entrypoints:
        - "web"
    titleadmin_app_frontend_secure:
      rule: '(Host(`{{ env "TITLE_ADMIN_APP_HOSTNAME" }}`) && PathPrefix(`/pdp`))'
      service: "titleadmin_app_frontend"
      entrypoints:
        - "web"
      middlewares:
        - titleadmin_app_forward_auth
    titleadmin_santander_frontend_secure:
      rule: '(Host(`{{ env "TITLE_ADMIN_APP_HOSTNAME" }}`) && PathPrefix(`/santander`))'
      service: "titleadmin_app_frontend"
      entrypoints:
        - "web"
      middlewares:
        - titleadmin_santander_forward_auth
    titleadmin_gmf_frontend_secure:
      rule: '(Host(`{{ env "TITLE_ADMIN_APP_HOSTNAME" }}`) && PathPrefix(`/gmf`))'
      service: "titleadmin_app_frontend"
      entrypoints:
        - "web"
      middlewares:
        - titleadmin_gmf_forward_auth
    titleadmin_ally_frontend_secure:
      rule: '(Host(`{{ env "TITLE_ADMIN_APP_HOSTNAME" }}`) && PathPrefix(`/ally`))'
      service: "titleadmin_app_frontend"
      entrypoints:
        - "web"
      middlewares:
        - titleadmin_ally_forward_auth
    titleadmin_app_auth_sidecar:
      rule: '(Host(`{{ env "TITLE_ADMIN_APP_HOSTNAME" }}`) && PathPrefix(`/auth_internal`))'
      service: "titleadmin_app_auth_sidecar"
      entrypoints:
        - "web"
    titleadmin_santander_auth_sidecar:
      rule: '(Host(`{{ env "TITLE_ADMIN_APP_HOSTNAME" }}`) && PathPrefix(`/auth_santander`))'
      service: "titleadmin_santander_auth_sidecar"
      entrypoints:
        - "web"
    titleadmin_gmf_auth_sidecar:
      rule: '(Host(`{{ env "TITLE_ADMIN_APP_HOSTNAME" }}`) && PathPrefix(`/auth_gmf`))'
      service: "titleadmin_gmf_auth_sidecar"
      entrypoints:
        - "web"
    titleadmin_ally_auth_sidecar:
      rule: '(Host(`{{ env "TITLE_ADMIN_APP_HOSTNAME" }}`) && PathPrefix(`/auth_ally`))'
      service: "titleadmin_ally_auth_sidecar"
      entrypoints:
        - "web"
    titleadmin_api_backend:
      rule: '(Host(`{{ env "TITLE_ADMIN_APP_HOSTNAME" }}`) && PathPrefix(`/graphql`))'
      service: "titleadmin_api_backend"
      entrypoints:
        - "web"
  middlewares:
    titleadmin_app_forward_auth:
      forwardAuth:
        address: "http://titleadmin_internal_auth_sidecar/auth_internal/verifyoidc"
        authResponseHeaders: 
          - X-Forwarded-User
          - X-Forwarded-UserId
          - X-Forwarded-User-EmailAddress
          - X-Forwarded-User-Role
          - X-Forwarded-User-Roles
          - X-Forwarded-User-FamilyName
          - X-Forwarded-User-MiddleName
          - X-Forwarded-User-GivenName
          - X-Forwarded-User-Name
          - X-Forwarded-User-Picture
          - X-Forwarded-Access-Token
          - X-Forwarded-Refresh-Token
          - X-Forwarded-User-Email-Verified
    titleadmin_santander_forward_auth:
      forwardAuth:
        address: "http://titleadmin_santander_auth_sidecar/auth_santander/verifyoidc"
        authResponseHeaders: 
          - X-Forwarded-User
          - X-Forwarded-UserId
          - X-Forwarded-User-EmailAddress
          - X-Forwarded-User-Role
          - X-Forwarded-User-Roles
          - X-Forwarded-User-FamilyName
          - X-Forwarded-User-MiddleName
          - X-Forwarded-User-GivenName
          - X-Forwarded-User-Name
          - X-Forwarded-User-Picture
          - X-Forwarded-Access-Token
          - X-Forwarded-Refresh-Token
          - X-Forwarded-User-Email-Verified
    titleadmin_gmf_forward_auth:
      forwardAuth:
        address: "http://titleadmin_gmf_auth_sidecar/auth_gmf/verifyoidc"
        authResponseHeaders: 
          - X-Forwarded-User
          - X-Forwarded-UserId
          - X-Forwarded-User-EmailAddress
          - X-Forwarded-User-Role
          - X-Forwarded-User-Roles
          - X-Forwarded-User-FamilyName
          - X-Forwarded-User-MiddleName
          - X-Forwarded-User-GivenName
          - X-Forwarded-User-Name
          - X-Forwarded-User-Picture
          - X-Forwarded-Access-Token
          - X-Forwarded-Refresh-Token
          - X-Forwarded-User-Email-Verified
    titleadmin_ally_forward_auth:
      forwardAuth:
        address: "http://titleadmin_ally_auth_sidecar/auth_ally/verifyoidc"
        authResponseHeaders: 
          - X-Forwarded-User
          - X-Forwarded-UserId
          - X-Forwarded-User-EmailAddress
          - X-Forwarded-User-Role
          - X-Forwarded-User-Roles
          - X-Forwarded-User-FamilyName
          - X-Forwarded-User-MiddleName
          - X-Forwarded-User-GivenName
          - X-Forwarded-User-Name
          - X-Forwarded-User-Picture
          - X-Forwarded-Access-Token
          - X-Forwarded-Refresh-Token
          - X-Forwarded-User-Email-Verified
    traefik_strip_prefix:
      stripPrefix:
        prefixes:
          - "/traefik"
