apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: beholder-state
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: beholder-redis:6379
  - name: redisPassword
    value: ""
  - name: enableTLS
    value: false
  - name: failover
    value: false
  - name: maxRetries
    value: 3
  - name: maxRetryBackoff
    value: 2000