apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: stalk
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
  - name: url
    value: "tcp://guest:guest@beholder-nexus:1883"
  - name: qos
    value: 0
  - name: retain
    value: "false"
  - name: cleanSession
    value: "true"