FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["./beholder-stalk.csproj", "."]
RUN dotnet restore "./beholder-stalk.csproj"
COPY . .
RUN dotnet build "beholder-stalk.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "beholder-stalk.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "beholder-stalk.dll"]
