FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["./beholder-occipital-v1.csproj", "."]
RUN dotnet restore "./beholder-occipital-v1.csproj"
COPY . .
RUN dotnet build "beholder-occipital-v1.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "beholder-occipital-v1.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "beholder-occipital-v1.dll"]
