name: Beholder - Build and Push Beholder Stalk v2 Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'beholder-stalk-v2/**'
      - '!beholder-stalk-v2/README.md'
      - '!beholder-stalk-v2/docs/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      working-directory: ./beholder-stalk-v2
      cache-key: beholder-stalk-v2

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.working-directory }}

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: beholderrpa/iot-stalk-v2
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Docker meta arm32v7
        id: docker_meta_arm32v7
        uses: docker/metadata-action@v3
        with:
          images: beholderrpa/iot-stalk-v2-arm32v7
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.cache-key }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-key }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.working-directory }}
          platforms: linux/amd64,linux/arm64
          file:  ${{ env.working-directory }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push arm32v7
        id: docker_build_arm32v7
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.working-directory }}
          file:  ${{ env.working-directory }}/Dockerfile.arm32v7
          push: true
          tags: ${{ steps.docker_meta_arm32v7.outputs.tags }}
          labels: ${{ steps.docker_meta_arm32v7.outputs.labels }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}